RRShop/RRShop/Areas/Admin/Controllers/ListController.cs
using Business.AdminBUS;
using Business.Business;
using Business.ViewModels;
using Connection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace RRShop.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ListController : Controller
    {
        public ActionResult CategoryList(int? CatID)
        {
            if (!CatID.HasValue)
            {
                CatID = 1;
            }
            Category cat = new Category();
            cat.CategoryID = (byte)CatID.Value;

            IEnumerable<Category> IlistCat = CategoryBUS.GetCategories();
            List<SelectListItem> listCat = new List<SelectListItem>();

            listCat.Add(new SelectListItem
            {
                Text = "-- Chọn loại --",
                Value = "-1"
            });

            foreach (var items in IlistCat)
            {
                listCat.Add(new SelectListItem
                {
                    Text = items.CategoryName,
                    Value = items.CategoryID.ToString(),
                    Selected = items.CategoryID == CatID ? true : false
                });
            }
            ViewBag.listCat = listCat;

            return View(cat);
        }

        public ActionResult SubCategoryList(int? SubCatID)
        {
            if (!SubCatID.HasValue)
            {
                SubCatID = 1;
            }
            SubCategory sub = new SubCategory();
            sub.SubCategoryID = (byte)SubCatID.Value;

            IEnumerable<SubCategoryViewModels> IlistSubCat = SubCategoryAdmin.GetSubCategoriesBySubCategory(SubCatID.Value);
            List<SelectListItem> listSubCat = new List<SelectListItem>();



            foreach (var items in IlistSubCat)
            {
                listSubCat.Add(new SelectListItem
                {
                    Text = items.SubCategoryName,
                    Value = items.SubCategoryID.ToString(),
                    Selected = items.SubCategoryID == SubCatID ? true : false
                });
            }
            ViewBag.listSubCat = listSubCat;

            return View(sub);
        }

        public ActionResult ProducerList(int? ProducerID)
        {
            if (!ProducerID.HasValue)
            {
                ProducerID = 1;
            }
            Producer producer = new Producer();
            producer.ProducerID = (short)ProducerID.Value;

            IEnumerable<ProducerViewModels> IlistProducer = ProducerViewModelsBUS.GetProducers();
            List<SelectListItem> listProducer = new List<SelectListItem>();

            listProducer.Add(new SelectListItem
            {
                Text = "-- Chọn NSX --",
                Value = "-1"
            });

            foreach (var items in IlistProducer)
            {
                listProducer.Add(new SelectListItem
                {
                    Text = items.ProducerName,
                    Value = items.ProducerID.ToString(),
                    Selected = items.ProducerID == ProducerID ? true : false
                });
            }
            ViewBag.listProducer = listProducer;
            return View(producer);
        }
    }
}

RRShop/RRShop/Areas/Admin/Controllers/ProductManagementController.cs
using Business.AdminBUS;
using Business.ViewModels;
using Connection;
using PetaPoco;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RRShop.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductManagementController : Controller
    {

        // GET: Admin/ProductManagement
        public ActionResult Index(short? id)
        {
            if (!id.HasValue)
            {
                id = 1;
            }
            return View(ProductAdmin.LoadProductByPage(id.Value));
        }

        public ActionResult Detail(short? ProID)
        {
            if (!ProID.HasValue)
            {
                ProID = 0;
            }
            return View(ProductAdmin.GetProductByID(ProID.Value));
        }

        [ValidateInput(false)]
        public ActionResult UpdateProduct(Product pro)
        {
            ProductAdmin.UpdateProduct(pro);
            return RedirectToAction("Detail", "ProductManagement", new { ProID = pro.ProductID});
        }

        public ActionResult Gallery(short? ProID)
        {
            FileUploadContainer fileUpload = new FileUploadContainer();
            if (!ProID.HasValue)
            { 
                ProID = 0;
            }

            ViewBag.ProName = ProductAdmin.GetProductNameByID(ProID.Value);
            fileUpload.ProductID = ProID.Value;
            return View(fileUpload);
        }

        [HttpPost]
        public ActionResult UploadImages(FileUploadContainer file)
        {
            if (file.Files.First() == null)
            {
                return RedirectToAction("ManageGallery/" + file.ProductID);
            }
            string path = Server.MapPath("~/images/product" + "/" + file.ProductID);
            string relativePath = "/images/product" + "/" + file.ProductID;
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            foreach (var item in file.Files)
            {
                if (item.ContentLength > 0)
                {
                    Image img = new Image();
                    img.ProductID = file.ProductID;
                    img.Link = relativePath + "/" + item.FileName;
                    img.IsMainImage = false;
                    ImageAdmin.InsertImage(img);
                    

                    var fileName = Path.GetFileName(item.FileName);
                    var thisPath = Path.Combine(path, fileName);
                    item.SaveAs(thisPath);
                }
            }

            return RedirectToAction("Gallery", new { ProID = file.ProductID });
        }

        public ActionResult ShowUploaded(short? ProID)
        {
            if (!ProID.HasValue)
            {
                ProID = 0;
            }
           
            return View(ImageAdmin.GetImageByProID(ProID.Value));
        }

        public ActionResult DeleteImg(Image img)
        {

            ImageAdmin.DeleteImage(img);
            string path = Server.MapPath(img.Link);
            if(path != null)
            {
                System.IO.File.Delete(path);
            }
            return RedirectToAction("Gallery", new { ProID = img.ProductID });
        }

        public ActionResult SetMainImg(Image img)
        {
            ImageAdmin.SetAllFalse(img.ProductID.Value);
            ImageAdmin.SetMainImg(img.ImageID);
            return RedirectToAction("Gallery", new { ProID = img.ProductID });
        }

        public ActionResult FormCreateProduct()
        {
            ProductViewModelForAdmin pro = new ProductViewModelForAdmin();
            return View(pro);
        }

        [ValidateInput(false)]
        public ActionResult CreateProduct(Product pro)
        {
            ProductAdmin.AddProduct(pro);
            return  RedirectToAction("FormCreateProduct");
        }

        public ActionResult AjaxGetSub(int CatID)
        {
            return Json(SubCategoryAdmin.GetSubCategoryByCategory(CatID), JsonRequestBehavior.AllowGet);
        }

        public ActionResult DeleteProduct(int ProID)
        {
            return Json(ProductAdmin.DeleteProduct(ProID), JsonRequestBehavior.AllowGet);
        }

    }
}

RRShop/RRShop/Areas/Admin/Views/ProductManagement/Detail.cshtml
@model Business.ViewModels.ProductViewModelForAdmin
@{
    ViewBag.Title = "Detail";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@if (Model != null)
{
<div class="page-title">
    <div class="title_left">
        <h3> Sản phẩm: @Model.ProductName</h3>
    </div>
    <div style="float: right">
        <a class="btn btn-default" style="background-color: #73879C; color: white" href="@Url.Action("Index")">Trở vê trang trước</a>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <br />
                @using (Html.BeginForm("UpdateProduct", "ProductManagement", FormMethod.Post, new { @class = "form-horizontal form-label-left" }))
                {
                    <input type="text" hidden="hidden" value="@Model.ProductID" name="ProductID" />
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Tên sản phẩm</label>
                        <div class="col-md-6 col-sm-9 col-xs-9">
                            @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Loại</label>
                        <div class="col-md-6 col-sm-9 col-xs-9">
                            @Html.Action("CategoryList", "List", new { CatID = Model.CategoryID })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Loại con</label>
                        <div class="col-md-6 col-sm-9 col-xs-9">
                            @Html.Action("SubCategoryList", "List", new { SubCatID = Model.SubCategoryID })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Nhà sản xuất</label>
                        <div class="col-md-6 col-sm-9 col-xs-9">
                            @Html.Action("ProducerList", "List", new { ProducerID = Model.ProducerID })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Số lượng</label>
                        <div class="col-md-6 col-sm-9 col-xs-9">
                            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Đơn giá</label>
                        <div class="col-md-6 col-sm-9 col-xs-9">
                            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Ngày cập nhật</label>
                        <div class="col-md-6 col-sm-9 col-xs-9">
                            @Html.TextBoxFor(model => model.UploadDate, "{0:MM-dd-yyyy}", new { @class = "form-control datepicker" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Mô tả</label>
                        <div class="col-md-7 col-sm-9 col-xs-9">
                            <textarea id="editor" name="Description">@Model.Description</textarea>
                            <script type="text/javascript">CKEDITOR.replace("editor");</script>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Hình ảnh</label>
                        <div class="col-md-7 col-sm-9 col-xs-9">
                            <a class="btn btn-default" href="@Url.Action("Gallery", new { ProID = Model.ProductID})">Xem hình ảnh sản phẩm</a>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-9 col-md-offset-3">
                            <button type="submit" class="btn btn-success">Submit</button>
                            <button type="button" class="btn btn-primary" id="bcancel">Cancel</button>                  
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

}
@section scripts
{
<script type="text/javascript">
    $(document).ready(function () {
        $('.datepicker').datepicker({
            dateFormat: "mm-dd-yy"
        });

        $('#bcancel').click(function () {
            $('<div></div>').appendTo('body')
            .html('<div><h6>Bạn có muốn huỷ bỏ những thay đổi?</h6></div>')
            .dialog({
                modal: true,
                title: 'Xác nhận',
                zIndex: 10000,
                autoOpen: true,
                width: '250px',
                resizable: false,
                buttons: {
                    Yes: function () {
                        location.reload();
                    },
                    No: function () {
                        $(this).dialog("close");
                    }
                },
                close: function (event, ui) {
                    $(this).remove();
                }
            });

        });

        $('#CategoryID').change(function () {
            $(this).find(":selected").each(function () {
                $.ajax({
                    type: 'GET',
                    dataType: 'json',
                    contentType: 'application/json',
                    url: '@Url.Action("AjaxGetSub")',
                    data: {
                        CatID: $(this).val()
                    },
                    success: function (result) {
                        var subID = $('#SubCategoryID');
                        subID.empty();
                        $(result).each(function () {
                            $(document.createElement('option'))
                                .attr('value', this.SubCategoryID)
                                .text(this.SubCategoryName)
                                .appendTo(subID);
                        });
                    }
                });
            });
        });
    });
</script>
}

RRShop/RRShop/Areas/Admin/Views/ProductManagement/FormCreateProduct.cshtml
@model Business.ViewModels.ProductViewModelForAdmin
@{
    ViewBag.Title = "FormCreateProduct";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-title">
    <div class="title_left">
        <h3> Thêm sản phẩm mới: </h3>
    </div>
    <div style="float: right">
        <a class="btn btn-default" style="background-color: #73879C; color: white" href="@Url.Action("Index")">Trở vê trang trước</a>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <br />
                @using (Html.BeginForm("CreateProduct", "ProductManagement", FormMethod.Post, new { @class = "form-horizontal form-label-left" }))
                {
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Tên sản phẩm</label>
                        <div class="col-md-6 col-sm-9 col-xs-9">
                            @Html.EditorFor(model => Model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Loại</label>
                        <div class="col-md-6 col-sm-9 col-xs-9">
                            @Html.Action("CategoryList", "List", new { CatID = 1 })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Loại con</label>
                        <div class="col-md-6 col-sm-9 col-xs-9">
                            @Html.Action("SubCategoryList", "List", new { SubCatID = 1 })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Nhà sản xuất</label>
                        <div class="col-md-6 col-sm-9 col-xs-9">
                            @Html.Action("ProducerList", "List", new { ProducerID = 1 })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Số lượng</label>
                        <div class="col-md-6 col-sm-9 col-xs-9">
                            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Đơn giá</label>
                        <div class="col-md-6 col-sm-9 col-xs-9">
                            @Html.EditorFor(model => Model.Price, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Ngày cập nhật</label>
                        <div class="col-md-6 col-sm-9 col-xs-9">
                            @*@Html.TextBoxFor(model => model, "{0:MM-dd-yyyy}", new { @class = "form-control datepicker" })*@
                            @Html.TextBox("UploadDate", DateTime.Now, "{0:MM-dd-yyyy}", new { @class = "form-control datepicker" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-3">Mô tả</label>
                        <div class="col-md-7 col-sm-9 col-xs-9">
                            <textarea id="editor" name="Description"></textarea>
                            <script type="text/javascript">CKEDITOR.replace("editor");</script>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-9 col-md-offset-3">
                            <button type="submit" class="btn btn-success">Submit</button>
                            <button type="button" class="btn btn-primary" id="bcancel">Cancel</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script type="text/javascript">
    $(document).ready(function () {
        $('.datepicker').datepicker({
            dateFormat: "mm-dd-yy"
        });

        $('#CategoryID').change(function () {
            $(this).find(":selected").each(function () {
                $.ajax({
                    type: 'GET',
                    dataType: 'json',
                    contentType: 'application/json',
                    url: '@Url.Action("AjaxGetSub")',
                    data: {
                        CatID: $(this).val()
                    },
                    success: function (result) {
                        var subID = $('#SubCategoryID');
                        subID.empty();
                        $(result).each(function () {
                            $(document.createElement('option'))
                                .attr('value', this.SubCategoryID)
                                .text(this.SubCategoryName)
                                .appendTo(subID);
                        });
                    }
                });
            });
        });
    });
    </script>
}

RRShop/RRShop/Areas/Admin/Views/ProductManagement/Gallery.cshtml
@model Business.ViewModels.FileUploadContainer
@{
    ViewBag.Title = "Gallery";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-title">
    <div class="title_left">
        <h3> Hình ảnh: @ViewBag.ProName </h3>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <h4>Phần upload ảnh:</h4>
        <div class="x_panel">
            <div class="x_content">
                @using (Html.BeginForm("UploadImages", "ProductManagement", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {

                    <input type="text" hidden="hidden" value="@Model.ProductID" name="ProductID" />
                    <input id="fileInputType" type="file" multiple class="fileUpload"
                           style="width:300px;" name="Files"><br />
                        <p style="color: #0066FF">
                            Click vào "Choose Files" để upload hình ảnh
                        </p>
                        <input type="submit" class="btn btn-success" value="Upload ảnh" />
                }
            </div>
        </div>
    </div>
</div>
<div class="row" style="margin-top: 20px">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <h4>Phần upload ảnh:</h4>
        <div class="x_panel">
            <div class="x_content">
                <h4>Hình ảnh của sản phẩm:</h4>
                @Html.Action("ShowUploaded", new { ProID = Model.ProductID })
            </div>
        </div>
    </div>
</div>

RRShop/RRShop/Areas/Admin/Views/ProductManagement/Index.cshtml
@model PetaPoco.Page<Business.ViewModels.ProductViewModels>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-title">
    <div class="title_left">
        <h3> Quản lý sản phẩm </h3>
    </div>
    <div style="float: right">
        <a class="btn btn-primary" href="@Url.Action("FormCreateProduct")">Thêm sản phâm mới</a>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <table class="table table-striped responsive-utilities jambo_table bulk_action">
                    <thead>
                        <tr class="headings">
                            <th class="column-title">ID </th>
                            <th class="column-title">Tên sản phẩm </th>
                            <th class="column-title">Loại SP </th>
                            <th class="column-title">Loại con </th>
                            <th class="column-title">Nhà sản xuất </th>
                            <th class="column-title">Giá bán </th>
                            <th class="column-title">Ngày ra mắt </th>
                            <th class="column-title no-link last">
                                <span class="nobr">Action</span>
                            </th>
                            <th class="bulk-actions" colspan="7">
                                <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                        </tr>
                    </thead>

                    <tbody>
@foreach (var item in Model.Items)
{
                        <tr class="even pointer">
                            <td>@item.ProductID</td>
                            <td>@item.ProductName</td>
                            <td>@item.CategoryName </td>
                            <td>@item.SubCategoryName</td>
                            <td>@item.ProducerName</td>
                            <td>@item.Price</td>
                            <td class="a-right a-right ">@item.UploadDate.ToShortDateString()</td>
                            <td class="last">
                                <a href="@Url.Action("Detail", new { ProID = item.ProductID })">Chi tiết</a> / 
                                <a style="cursor:pointer" id="@String.Format("ProID{0}", item.ProductID)"  data-ProID="@item.ProductID" data-ProName="@item.ProductName">Xoá</a> / 
                                <a href="@Url.Action("Gallery", new { ProID = item.ProductID })">Hình ảnh</a>
                            </td>
                        </tr>
}
                    </tbody>
                </table>
                <ul class="pagination" style="float:right">
                    @for (int i = 1; i <= Model.TotalPages; i++)
                    {
                        if (i == Model.CurrentPage)
                        {
                            <li class="active"><a href="@Url.Action("Index", new { id = i})">@i</a></li>
                        }
                        else
                        {
                            <li><a href="@Url.Action("Index", new { id = i})">@i</a></li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
</div>
@section scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            $("a[id*='ProID']").click(function () {
                var id = $(this).attr('data-ProID');
                var name = $(this).attr('data-ProName');
                var item = $(this).parent().parent();
                $('<div></div>').appendTo('body')
                .html('<div><h6>Bạn có muốn xoá sản phẩm ' + name + '?</h6></div>')
                .dialog({
                    modal: true,
                    title: 'Xác nhận',
                    zIndex: 10000,
                    autoOpen: true,
                    width: '250px',
                    resizable: false,
                    buttons: {
                        Yes: function () {
                            $.ajax({
                                type: 'GET',
                                url: '@Url.Action("DeleteProduct")',
                                data: {
                                    ProID: id
                                },
                                success: function (result) {
                                    item.fadeOut();  
                                }
                            });
                            $(this).dialog("close");
                            
                        },
                        No: function () {
                            $(this).dialog("close");
                        }
                    },
                    close: function (event, ui) {
                        $(this).remove();
                    }
                });
            });
        });
    </script>
}

RRShop/RRShop/Areas/Admin/Views/ProductManagement/ShowUploaded.cshtml
@model IEnumerable<Connection.Image>
@{ 
    Layout = null;
}

@foreach (var item in Model)
{
<div class="col-md-55">
    <div class="thumbnail" style="height: 240px">
        <div class="image view view-first" style="height: 200px">
            <img style="width: 100%; height: 100%; display: block;" src="@item.Link" alt="image" />
            <div class="mask">
                @if (item.IsMainImage.Value)
                {
                    <p>Ảnh đại diện</p>
                }
                
                <div class="tools tools-bottom">
                    <a href="@Url.Action("SetMainImg", item)"><i class="fa fa-pencil"></i></a>
                    <a href="@Url.Action("DeleteImg", item)"><i class="fa fa-times"></i></a>
                </div>
            </div>
        </div>
        <div class="caption">
            @if (item.IsMainImage.Value)
            {
                <p>Ảnh đại diện</p>
            }
        </div>
    </div>
</div>
}