RRShop/RRShop/Controllers/CatalogSearchController.cs
using Business.AdminBUS;
using Business.Business;
using Business.ViewModels;
using Connection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RRShop.Controllers
{
    [RoutePrefix("CatalogSearch")]
    public class CatalogSearchController : Controller
    {
        [Route("")]
        // GET: CatalogSearch
        public ActionResult Index()
        {
            return View();
        }

        [Route("Result")]
        public ActionResult Result(int? page, string keyword = "")
        {
            if (keyword == "")
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.keyword = keyword;
            return View(Searching.NormalSearch(keyword, page));
        }


        [Route("AdvancedResult")]
        public ActionResult AdvancedResult(SearchItems item, int? page)
        {
            ViewBag.SearchItems = item;
            return View(Searching.AdvancedSearch(item, page));
        }
        public ActionResult _CategoryList()
        {
            Category cat = new Category();

            IEnumerable<Category> IlistCat = CategoryBUS.GetCategories();
            List<SelectListItem> listCat = new List<SelectListItem>();

            listCat.Add(new SelectListItem {
                Text = "-- Chọn loại --",
                Value = "-1"
            });

            foreach (var items in IlistCat)
            {
                listCat.Add(new SelectListItem
                {
                    Text = items.CategoryName,
                    Value = items.CategoryID.ToString(),
                });
            }
            ViewBag.listCat = listCat;

            return View(cat);
        }

        public ActionResult _ProducerList()
        {

            Producer producer = new Producer();

            IEnumerable<ProducerViewModels> IlistProducer = ProducerViewModelsBUS.GetProducers();
            List<SelectListItem> listProducer = new List<SelectListItem>();

            listProducer.Add(new SelectListItem
            {
                Text = "-- Chọn NSX --",
                Value = "-1"
            });

            foreach (var items in IlistProducer)
            {
                listProducer.Add(new SelectListItem
                {
                    Text = items.ProducerName,
                    Value = items.ProducerID.ToString()
                });
            }
            ViewBag.listProducer = listProducer;
            return View(producer);
        }

        public ActionResult AjaxGetSub(int CatID)
        {
            return Json(SubCategoryAdmin.GetSubCategoryByCategory(CatID), JsonRequestBehavior.AllowGet);
        }
    }
}

RRShop/RRShop/Controllers/MenuController.cs
using Business.Business;
using Business.ViewModels;
using System.Web.Mvc;

namespace RRShop.Controllers
{
    public class MenuController : Controller
    {
        public ActionResult _MenuPartial()
        {
            if (!ControllerContext.IsChildAction)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(new MenuViewModels());
        }

        public ActionResult _MobileMenuPartial()
        {
            if (!ControllerContext.IsChildAction)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(new MenuViewModels());
        }

        public ActionResult _FooterMenuPartial()
        {
            if (!ControllerContext.IsChildAction)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(CategoryViewModelsBUS.GetCategories());
        }

        public ActionResult _LeftMenuPartial()
        {
            if (!ControllerContext.IsChildAction)
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }
    }
}

RRShop/RRShop/Views/CatalogSearch/Result.cshtml
@model PetaPoco.Page<Business.ViewModels.ProductViewModels>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    bool isSaled = false;
    int count = 0;
    int countX3 = 0;
    Business.ViewModels.ProductViewModels element;
}

<div class="main-container col2-left-layout">
    @*Start Link Previous*@
    <div class="breadcrumbs">
        <div class="container">
            <ul>
                <li class="home">
                    <a href="@Url.Action("Index", "Home")" title="Về trang chủ">Trang chủ</a>
                    <span></span>
                </li>

                @*Start Category Name*@
                <li class="category3">
                    <strong>Kết quả tìm từ khoá: '@ViewBag.keyword'</strong>
                </li>
                @*End Category Name*@
            </ul>
        </div>
    </div>
    @*End Link Previous*@

    <div class="container">
        <div class="main">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <p class="category-image"></p>
                </div>

                @*Start Left Menu*@
                @Html.Action("_LeftMenuPartial", "Menu")
                @*End Left Menu*@

                <div class="col-main col-xs-12 col-sm-9">
                    <div class="category-products">
                        <div class="toolbar">
                            <div class="pager">
                                @*Start Sort Product Information*@
                                <div class="sort-by hidden-xs">
                                    <label></label>
                                </div>
                                @*End Sort Product Information*@
                            </div>

                            <div class="sorter">
                                @*Start Show Number of Products per Page*@
                                <div class="limiter hidden-xs">
                                    <label></label>
                                    <div class="limiter-inner">
                                    </div>
                                </div>
                                @*End Show Number of Products per Page*@

                                @*Start Page List*@
                                <div class="pages">
                                    <ol>
                                        @if (Model.CurrentPage > 1)
                                        {
                                            <li>
                                                <a class="previous i-previous" href="@Url.Action("Result", "CatalogSearch", new { keyword = ViewBag.keyword, page = Model.CurrentPage - 1 })"></a>
                                            </li>
                                        }

                                        @*Start Code Here*@
                                        @for (int i = 1; i <= Model.TotalPages; i++)
                                        {
                                            if (i == Model.CurrentPage)
                                            {
                                                <li class="current">@i</li>
                                            }
                                            else
                                            {
                                                <li>
                                                    <a href="@Url.Action("Result", "CatalogSearch", new { keyword = ViewBag.keyword, page = i })">
                                                        @i
                                                    </a>
                                                </li>
                                            }
                                        }
                                        @*End Code*@

                                        @if (Model.CurrentPage < Model.TotalPages)
                                        {
                                            <li>
                                                <a class="next i-next" href="@Url.Action("Result", "CatalogSearch", new { keyword = ViewBag.keyword, page = Model.CurrentPage + 1 })"></a>
                                            </li>
                                        }
                                    </ol>
                                </div>
                                @*End Page List*@
                            </div>
                        </div>

                        @*Start Product List*@
                        <div class="product-grid-container">
                            @while (count < Model.Items.Count)
                            {
                                countX3 = count + 3 <= Model.Items.Count ? count + 3 : Model.Items.Count;

                                <ul class="products-grid row">
                                    @*Start An Item*@
                                    @for (var i = count; i < countX3; i++)
                                    {
                                        element = Model.Items[i];
                                        isSaled = element.SalePrice == 0 ? false : true;

                                        <li class="ma-item_slider col-md-4 col-sm-4 col-sms-12 col-smb-12 item">
                                            <div class="item-inner">
                                                <div class="images-container">
                                                    @*Start Product Image*@
                                                    <a href="@Url.Action("Detail", "Product", new { id = element.ProductID, name = element.RouteName })" class="product-image">
                                                        <img src="@(element.Images.Count > 0 ? element.Images[0].Link : "/images/no-image/268.jpg")" id="product-collection-image-@(i + 1)" />
                                                    </a>
                                                    @*End Product Image*@

                                                    @*Start Button*@
                                                    <div class="actions">
                                                        <ul class="add-to-links">
                                                            <li>
                                                                <a class="link-wishlist">
                                                                    <em class="tooltip">Yêu thích</em>
                                                                </a>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                    @*End Button*@

                                                    @*Start Product Price*@
                                                    <div class="price-box @(!isSaled ? "box-regular" : "box-special")">
                                                        @if (isSaled)
                                                        {
                                                            <p class="special-price">
                                                                <span class="price">@element.SalePrice.ToString("##,#")</span>
                                                            </p>
                                                        }

                                                        <p class="@(!isSaled ? "regular-price" : "old-price")">
                                                            <span class="price">@element.Price.ToString("##,#")</span>
                                                        </p>
                                                    </div>
                                                    @*End Product Price*@
                                                </div>

                                                @*Start Product Main Information*@
                                                <div class="des-container">
                                                    <h2 class="product-name">
                                                        <a href="@Url.Action("Detail", "Product", new { id = element.ProductID, name = element.RouteName })">
                                                            @element.ProductName
                                                        </a>
                                                    </h2>

                                                    <div class="ma-desc"></div>

                                                    <button type="button" title="Add to Cart" class="button btn-cart">
                                                        <span><span>Add to Cart</span></span>
                                                    </button>
                                                </div>
                                                @*End Product Main Information*@
                                            </div>
                                        </li>
                                    }
                                    @*End An Item*@
                                </ul>

                                count += 3;
                            }
                        </div>
                        @*End Product List*@

                        @*Start Paging*@
                        @if (Model.TotalPages > 1)
                        {
                            <div class="toolbar-bottom">
                                <div class="toolbar">
                                    <ul class="paging">
                                        @if (Model.CurrentPage > 1)
                                        {
                                            <li>
                                                <a class="prev" href="@Url.Action("Result", "CatalogSearch", new {  keyword = ViewBag.keyword, page = Model.CurrentPage - 1 })"></a>
                                            </li>
                                        }

                                        @for (int i = 1; i <= Model.TotalPages; i++)
                                        {
                                            <li>
                                                @if (i == Model.CurrentPage)
                                                {
                                                    <a class="current">@i</a>
                                                }
                                                else
                                                {
                                                    <a href="@Url.Action("Result", "CatalogSearch", new { keyword = ViewBag.keyword, page = i })">@i</a>
                                                }
                                            </li>
                                        }

                                        @if (Model.CurrentPage < Model.TotalPages)
                                        {
                                            <li>
                                                <a class="next" href="@Url.Action("Result", "CatalogSearch", new { keyword = ViewBag.keyword, page = Model.CurrentPage + 1 })"></a>
                                            </li>
                                        }
                                    </ul>
                                </div>
                            </div>
                        }
                        @*End Paging*@
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts
{
    <script type="text/javascript">
        $("#price_range").ionRangeSlider({
            type: "double",
            grid: true,
            min: 0,
            max: 100000000,
            from: 0,
            to: 100000000,
            onFinish: function (data) {
                $('#price_from').val(data.from);
                $('#price_to').val(data.to);
                console.log($('#price_from').val());
                console.log($('#price_to').val());
            }
        });

        $('#CategoryID').change(function () {
            $(this).find(":selected").each(function () {
                $.ajax({
                    type: 'GET',
                    dataType: 'json',
                    contentType: 'application/json',
                    url: '@Url.Action("AjaxGetSub")',
                    data: {
                        CatID: $(this).val()
                    },
                    success: function (result) {
                        var subID = $('#SubCategoryID');
                        subID.empty();

                        $(document.createElement('option'))
                                .attr('value', '-1')
                                .text('-- Chọn loại con --')
                                .appendTo(subID);

                        $(result).each(function () {
                            $(document.createElement('option'))
                                .attr('value', this.SubCategoryID)
                                .text(this.SubCategoryName)
                                .appendTo(subID);
                        });
                    }
                });
            });
        });
    </script>
}

RRShop/RRShop/Views/CatalogSearch/_CategoryList.cshtml
@model Connection.Category
@{
    Layout = null;
}

@Html.DropDownListFor(model => model.CategoryID, ViewBag.listCat as IEnumerable<SelectListItem>, new { @class = "form-control" })

RRShop/RRShop/Views/CatalogSearch/_ProducerList.cshtml
@model Connection.Producer
@{
    Layout = null;
}

@Html.DropDownListFor(model => model.ProducerID, ViewBag.listProducer as IEnumerable<SelectListItem>, new { @class = "form-control" })