RRShop/RRShop/Controllers/CategoryController.cs
using Business.Business;
using System.Web.Mvc;

namespace RRShop.Controllers
{
    [RoutePrefix("Cat")]
    public class CategoryController : Controller
    {
        [Route("{id}/{name}/{page?}")]
        public ActionResult Cat(int? page, string name = "", int id = 0)
        {
            if (id == 0 || name == "")
            {
                return RedirectToAction("Index", "Home");
            }

            ViewBag.Category = CategoryViewModelsBUS.GetCategoriesWithBanner(id);

            return View(ProductViewModelsBUS.GetProductsByCategory(id, page));
        }

        [Route("{id}/{name}/Sub/{subId}/{subname}/{page?}")]
        public ActionResult Sub(int? page, int id = 0, string name = "", byte subId = 0, string subname = "")
        {
            if (id == 0 || subname == "" || name == "" || subId == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            ViewBag.Category = CategoryViewModelsBUS.GetCategoryById(id);

            ViewBag.SubCategoryName = SubCategoryViewModelsBUS.GetSubCategoryNameById(subId);

            ViewBag.SubCategoryID = subId;
            ViewBag.SubCategoryRouteName = subname;

            return View(ProductViewModelsBUS.GetProductsBySubCategory(subId, page));
        }
    }
}

RRShop/RRShop/Controllers/HomeController.cs
using Business.Business;
using System.Web.Mvc;

namespace RRShop.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.ClassBody = "cms-index-index cms-home";
            ViewBag.HasSale = Library.HasSale();

            return View();
        }

        public ActionResult _FeatureCategoryPartial()
        {
            if (!ControllerContext.IsChildAction)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(CategoryViewModelsBUS.GetCategoriesWithImage());
        }

        public ActionResult _TopNewPartial()
        {
            if (!ControllerContext.IsChildAction)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(ProductViewModelsBUS.GetTopNewProducts());
        }

        public ActionResult _TopSellerPartial()
        {
            if (!ControllerContext.IsChildAction)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(ProductViewModelsBUS.GetTopSellerProducts());
        }

        public ActionResult _TopSalePartial()
        {
            if (!ControllerContext.IsChildAction)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(ProductViewModelsBUS.GetTopSaledProducts());
        }

        public ActionResult _MostViewedPartial()
        {
            if (!ControllerContext.IsChildAction)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(ProductViewModelsBUS.GetTopViewedProducts());
        }

        public ActionResult _HotSalePartial()
        {
            if (!ControllerContext.IsChildAction)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(ProductViewModelsBUS.GetHotSaleProducts());
        }
    }
}

RRShop/RRShop/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="main-container col1-layout">
    @*Start Banner*@
    <div class="ma-banner7-container">
        <div class="flexslider ma-nivoslider">
            <div id="ma-inivoslider-banner7" class="slides">
                <a href="@Url.Action("Cat", "Category", new { id = 1, name = "Laptop" })" title="Read more">
                    <img style="display: none;" src="~/images/slideshow/background/bg_home_slider1.jpg" alt="" title="#banner7-caption1" />
                </a>

                <a href="@Url.Action("Cat", "Category", new { id = 4, name = "Hardware" })" title="Read more">
                    <img style="display: none;" src="~/images/slideshow/background/bg_home_slider2.jpg" alt="" title="#banner7-caption2" />
                </a>
            </div>

            <div id="banner7-caption1" class="banner7-caption nivo-html-caption nivo-caption">
                <div class="banner7-content slider-1">
                    <div class="text-content">
                        <div class="title-container">
                            <h1 class="title1">Laptop</h1>
                        </div>
                        <div class="banner7-des">
                            Hàng chất lượng - giá hợp lý
                        </div>
                        <div class="banner7-readmore">
                            <a href="@Url.Action("Cat", "Category", new { id = 1, name = "Laptop" })" title="Read more">Mua ngay</a>
                        </div>
                    </div>

                    <img class="img1" src="~/images/slideshow/1.png" alt="" />
                </div>
            </div>

            <div id="banner7-caption2" class="banner7-caption nivo-html-caption nivo-caption">
                <div class="banner7-content slider-2">
                    <div class="text-content">
                        <div class="title-container">
                            <h1 class="title1">linh kiện</h1>
                        </div>
                        <div class="banner7-des">
                            Linh kiện giá mềm - hàng chính hãng 100%
                        </div>
                        <div class="banner7-readmore">
                            <a href="@Url.Action("Cat", "Category", new { id = 4, name = "Hardware" })" title="Read more">Mua ngay</a>
                        </div>
                    </div>

                    <img class="img1" src="~/images/slideshow/14.png" alt="" />
                </div>
            </div>
        </div>
    </div>
    @*End Banner*@

    @*Start Introduce*@
    <div class="banner-static-top">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-3 col-sms-6 col-smb-12">
                    <div class="banner-box banner-box1">
                        <div class="box-inner">
                            <span class="image free-ship"></span>
                            <div class="text">
                                <a class="name" href="#">Giao hàng miễn phí</a>
                                <p>
                                    Giao hàng miễn phí cho các khách hàng ở trung tâm thành phố.
                                    Khách hàng vui lòng kiểm tra sản phẩm kỹ lưỡng trước khi nhận hàng.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-3 col-sm-3 col-sms-6 col-smb-12">
                    <div class="banner-box banner-box2">
                        <div class="box-inner">
                            <span class="image return"></span>
                            <div class="text">
                                <a class="name" href="#">Hoàn trả sản phẩm</a>
                                <p>
                                    Các sản phẩm của cửa được hoàn trả miễn phí trong vòng 3 ngày kể từ ngày mua.
                                    Sản phẩm phải còn tem bảo hành và nguyên vẹn theo quy định của giấy bảo hành.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-3 col-sm-3 col-sms-6 col-smb-12">
                    <div class="banner-box banner-box3">
                        <div class="box-inner">
                            <span class="image gift"></span>
                            <div class="text">
                                <a class="name" href="#">Ưu đãi</a>
                                <p>
                                    Cửa hàng có các đợt ưu đãi với các sản phẩm có giá hấp dẫn.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-3 col-sm-3 col-sms-6 col-smb-12">
                    <div class="banner-box banner-box4">
                        <div class="box-inner">
                            <span class="image support"></span>
                            <div class="text">
                                <a class="name" href="#">Hổ trợ</a>
                                <p>
                                    Nếu có thắc mắc, quý khách xin vui lòng liên hệ chúng tôi để nhận được sự hổ trợ.
                                    Thời gian làm việc trong giờ hành chánh, trừ thứ bảy và chủ nhật.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @*End Introduce*@

    @*Start Top Products*@
    <div class="container">
        <div class="main">
            <div class="col-main">
                <div class="std">
                    <div class="home-content">
                        <div class="producttabs">
                            <div class="tab-container">
                                <ul id="producttabs">
                                    <li class="item first active"><h3 class="new">Sản phẩm mới</h3></li>

                                    <li class="item"><h3 class="featured">Được mua nhiều nhất</h3></li>

                                    @if (ViewBag.HasSale)
                                    {
                                        <li class="item last"><h3 class="sale">Khuyến mãi</h3></li>
                                    }
                                </ul>
                            </div>

                            <div class="content">
                                @*Start Top New Products*@
                                @Html.Action("_TopNewPartial", "Home")
                                @*End Top New Products*@

                                @*Start Top Seller Products*@
                                @Html.Action("_TopSellerPartial", "Home")
                                @*End Top Seller Products*@

                                @*Start Top Sale Products*@
                                @if (ViewBag.HasSale)
                                {
                                    @Html.Action("_TopSalePartial", "Home")
                                }
                                @*End Top Sale Products*@
                            </div>
                        </div>
                    </div>
                </div>

                @*Start Banner*@
                <div class="banner-static">
                    <div class="row">
                        <div class="col-sm-6 col-sms-12">
                            <div class="banner-box banner-box1">
                                <div class="box-inner">
                                    <a href="@Url.Action("Cat", "Category", new { id = 3, name = "Tablet" })">
                                        <img src="~/images/slideshow/banner1.jpg" />
                                    </a>

                                    <div class="text">
                                        <h1>Tablet</h1>
                                        <p>Hàng chính hãng, chất lượng</p>
                                        @*<a class="shop-now" href="http://demo4plazathemes.com/19/ma_flaton/index.php/smart-phone.html">shop now</a>*@
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6 col-sms-12">
                            <div class="banner-box banner-box2">
                                <div class="box-inner">
                                    <a href="@Url.Action("Cat", "Category", new { id = 3, name = "PC" })">
                                        <img src="~/images/slideshow/banner2.png" />
                                    </a>

                                    <div class="text">
                                        <h1>PC</h1>
                                        <p>Hàng chất lượng cao</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @*End Banner*@

                @*Start Offers*@
                @if (ViewBag.HasSale)
                {
                    @Html.Action("_HotSalePartial", "Home")
                }
                @*End Offers*@
            </div>
        </div>
    </div>
    @*End Top Products*@
</div>

@*Start Category Banner*@
@Html.Action("_FeatureCategoryPartial", "Home")
@*End Category Banner*@

<div class="featured-categories"></div>

@*Start Most Viewed Products*@
@Html.Action("_MostViewedPartial", "Home")
@*End Most Viewed Products*@

@*<div class="testimonial-sidebar">
        <div class="container">
            <div class="modul-title2">
                <h2>What Our Clients Say</h2>
            </div>

            <div class="block-content">
                <div class="owl-container">
                    <div class="owl">
                        <div class='testimonial-list'>
                            <div class="testimonial-sidebar-content">
                                <div class="content">
                                    <a href="http://demo4plazathemes.com/19/ma_flaton/index.php/testimonial/">
                                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat...
                                    </a>
                                </div>
                            </div>
                        </div>

                        <div class='testimonial-list'>
                            <div class="testimonial-sidebar-content">
                                <div class="content">
                                    <a href="http://demo4plazathemes.com/19/ma_flaton/index.php/testimonial/">
                                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <ul class="thumb">
                    <li onclick="testislider(0)" class="testithumb0 active"><img src="http://demo4plazathemes.com/19/ma_flaton/media/magentothem/avatar/banner_bottom3.jpg" alt="test" height="120" width="120" /></li>

                    <li onclick="testislider(1)" class="testithumb1 "><img src="http://demo4plazathemes.com/19/ma_flaton/media/magentothem/avatar/testimonial_avata1.png" alt="test" height="120" width="120" /></li>
                </ul>
            </div>
        </div>
    </div>*@

RRShop/RRShop/Views/Home/_FeatureCategoryPartial.cshtml
@model IEnumerable<Business.ViewModels.CategoryViewModels>

@{
    Layout = null;
}

<div class="catthumb">
    <div class="modul-title2">
        <h2>
            Danh mục
        </h2>
    </div>

    <ul id="catthumb" catNum="@(Model.Count() + 1)">
        @foreach (var element in Model)
        {
            <li class="item">
                <div class="box-cate">
                    <div class="image">
                        <a href="@Url.Action("Cat", "Category", new { id = element.CategoryID, name = element.RouteName })">
                            <span class="icon"><img src="@element.Image" /></span>
                        </a>
                    </div>

                    <h3 class="name-cate">@element.CategoryName</h3>
                </div>
            </li>
        }

        <li class="item">
            <div class="box-cate">
                <div class="image">
                    <a href="@Url.Action("Index", "Sale")">
                        <span class="icon"><img src="~/images/category/Sale.png" /></span>
                    </a>
                </div>

                <h3 class="name-cate">Khuyến mãi</h3>
            </div>
        </li>
    </ul>
</div>

RRShop/RRShop/Views/Home/_HotSalePartial.cshtml
@model List<Business.ViewModels.ProductViewModels>

@{
    Layout = null;
    int i = 1;
}

<div class="ma-timer-container">
    <div class="ma-timer-title modul-title1"><h2>Sản phẩm nổi bật</h2></div>
    <div class="row">
        <div class="col-sm-2 col-sms-12">
            <ul class="thumb">
                @for (int index = 0; index < Model.Count; i++)
                {
                    <li class="thumb@(i)  active @(i != 0 ? "" : "first")" data-owl="@i">
                        @if (Model[i].Quantity == 0)
                        {
                            <img src="~/images/notification/soldout.png" class="soldOut" />
                        }
                        <img src="@(Model[i].Images.Count > 0 ? Model[i].Images[0].Link : "/images/no-image/268.jpg")" />
                    </li>
                }
            </ul>
        </div>

        <div class="col-sm-10 col-sms-12">
            <div class="modul-tab-content">
                <div class="owl">
                    @foreach (var element in Model)
                    {
                        <div class='timer-item'>
                            <div class="timer_product">
                                <div class="box-timer">
                                    <div id="heading@(i)" style="color:#FFFFFF;clear: both;"></div>
                                    <div class="countbox_@(i) timer-grid"></div>
                                </div>

                                <div class="row">
                                    <div class="col-sm-6 col-sms-6 col-smb-12">
                                        <div class="des-container">
                                            <h2 class="product-name">
                                                <a href="@Url.Action("Detail", "Product", new { id = element.ProductID, name = element.RouteName })">
                                                    @element.ProductName
                                                </a>
                                            </h2>

                                            @*<div class="ratings">
                                                    <div class="rating-box">
                                                        <div class="rating" style="width:73%"></div>
                                                    </div>
                                                    <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='http://demo4plazathemes.com/19/ma_flaton/index.php/review/product/list/id/2/'; return false;">1 Review(s)</a></span>
                                                </div>*@

                                            <div class="ma-desc">

                                            </div>

                                            <div class="price-box">
                                                <p class="old-price">
                                                    <span class="price">@element.Price.ToString("##,#")</span>
                                                </p>

                                                <p class="special-price">
                                                    <span class="price">@element.SalePrice.ToString("##,#")</span>
                                                </p>
                                            </div>

                                            <div class="actions">
                                                <button type="button" class="button btn-cart" data-proId="@element.ProductID" @(element.Quantity == 0 ? "disabled" : "")>
                                                    <span><span>Thêm vào giỏ hàng</span></span>
                                                </button>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-sm-6 col-sms-6 col-smb-12">
                                        <div class="images-container">
                                            <a href="@Url.Action("Detail", "Product", new { id = element.ProductID, name = element.RouteName })" class="product-image">
                                                <img src="@(element.Images.Count > 0 ? element.Images[0].Link : "/images/no-image/268.jpg")" />
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

RRShop/RRShop/Views/Home/_MostViewedPartial.cshtml
@model List<Business.ViewModels.ProductViewModels>

@{
    Layout = null;
    bool isSale = false;
}

<div class="ma-mostviewedproductslider-container">
    <div class="container">
        <div class="ma-mostviewedproductslider-title modul-title1"><h2>Được xem nhiều nhất</h2></div>
        <div class="owl-container">
            <div class="owl">
                @foreach (var element in Model)
                {
                    isSale = element.SalePrice == 0 ? false : true;

                    <div class='mostviewedproductslider-item item'>
                        <div class="item-inner">
                            <div class="images-container">
                                <a href="@Url.Action("Detail", "Product", new { id = element.ProductID, name = element.RouteName })" class="product-image">
                                    @if (element.Quantity == 0)
                                    {
                                        <img src="~/images/notification/soldout.png" class="soldOut" />
                                    }
                                    <img src="@(element.Images.Count > 0 ? element.Images[0].Link : "/images/no-image/268.jpg")" />
                                </a>

                                <div class="actions">
                                    <ul class="add-to-links">
                                        <li>
                                            <a class="link-wishlist">
                                                <em class="tooltip">Yêu thích</em>
                                            </a>
                                        </li>

                                        @*<li>
                                                <span class="separator">|</span>

                                                <a href="http://demo4plazathemes.com/19/ma_flaton/index.php/catalog/product_compare/add/product/15/uenc/aHR0cDovL2RlbW80cGxhemF0aGVtZXMuY29tLzE5L21hX2ZsYXRvbi9pbmRleC5waHAv/form_key/mdZfgJRbAoMhqUUv/" class="link-compare">
                                                    <em class="tooltip">compare</em>Add to Compare
                                                </a>
                                            </li>*@
                                    </ul>
                                </div>

                                <div class="price-box @(!isSale ? "box-regular" : "box-special")">
                                    @if (isSale)
                                    {
                                        <p class="special-price">
                                            <span class="price">@element.SalePrice.ToString("##,#")</span>
                                        </p>
                                    }

                                    <p class="@(!isSale ? "regular-price" : "old-price")">
                                        <span class="price">@element.Price.ToString("##,#")</span>
                                    </p>
                                </div>
                            </div>

                            <div class="des-container">
                                <h2 class="product-name">
                                    <a href="@Url.Action("Detail", "Product", new { id = element.ProductID, name = element.RouteName })">
                                        @element.ProductName
                                    </a>
                                </h2>

                                @*<div class="ratings">
                                        <div class="rating-box">
                                            <div class="rating" style="width:60%"></div>
                                        </div>

                                        <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='http://demo4plazathemes.com/19/ma_flaton/index.php/review/product/list/id/15/'; return false;">1 Review(s)</a></span>
                                    </div>*@

                                <button type="button" class="button btn-cart" data-proId="@element.ProductID" @(element.Quantity == 0 ? "disabled" : "")>
                                    <span><span>Thêm vào giỏ hàng</span></span>
                                </button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

RRShop/RRShop/Views/Home/_TopNewPartial.cshtml
@model List<Business.ViewModels.ProductViewModels>

@{
    Layout = null;
    int count = 0;
    int countX2 = 0;
    bool isSale = false;
}

<div id="producttab_new" class="tab active">
    <div class="mage-products">
        <div class="owl-container">
            <div class="producttabs-products-owl">
                @while (count < Model.Count)
                {
                    countX2 = count + 2 <= Model.Count ? count + 2 : Model.Count;

                    <div class='item'>
                        @for (var i = count; i < countX2; i++)
                        {
                            isSale = Model[i].SalePrice == 0 ? false : true;

                            <div class="item-inner">
                                <div class="images-container">
                                    <a href="@Url.Action("Detail", "Product", new { id = Model[i].ProductID, name = Model[i].RouteName })" class="product-image">
                                        @if (Model[i].Quantity == 0)
                                        {
                                            <img src="~/images/notification/soldout.png" class="soldOut" />
                                        }
                                        <img src="@(Model[i].Images.Count > 0 ? Model[i].Images[0].Link : "/images/no-image/268.jpg")" />
                                    </a>

                                    <div class="actions">
                                        <ul class="add-to-links">
                                            <li>
                                                <a class="link-wishlist">
                                                    <em class="tooltip">Yêu thích</em>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>

                                    <div class="price-box @(!isSale ? "box-regular" : "box-special")">
                                        @if (isSale)
                                        {
                                            <p class="special-price">
                                                <span class="price">@(Model[i].SalePrice.ToString("##,#"))</span>
                                            </p>
                                        }

                                        <p class="@(!isSale ? "regular-price" : "old-price")">
                                            <span class="price">@(Model[i].Price.ToString("##,#"))</span>
                                        </p>
                                    </div>
                                </div>

                                <div class="des-container">
                                    <h2 class="product-name">
                                        <a href="@Url.Action("Detail", "Product", new { id = Model[i].ProductID, name = Model[i].RouteName })">
                                            @Model[i].ProductName
                                        </a>
                                    </h2>

                                    <button type="button" class="button btn-cart" data-proId="@Model[i].ProductID" @(Model[i].Quantity == 0 ? "disabled" : "")>
                                        <span><span>Thêm vào giỏ hàng</span></span>
                                    </button>
                                </div>
                            </div>
                        }
                    </div>

                    count += 2;
                }
            </div>
        </div>
    </div>
</div>